insert into posts (title, body, user_id) values ('My Friend Irma Goes West', 'Displaced oblique fracture of shaft of unspecified ulna, subsequent encounter for open fracture type I or II with nonunion', 1);
insert into posts (title, body, user_id) values ('Journey of August King, The', 'Monteggia''s fracture of left ulna, initial encounter for open fracture type IIIA, IIIB, or IIIC', 1);
insert into posts (title, body, user_id) values ('Judy Moody and the Not Bummer Summer', 'Legal intervention involving other firearm discharge, law enforcement official injured, initial encounter', 1);
insert into posts (title, body, user_id) values ('Incident at Loch Ness', 'Superficial frostbite of left hand', 1);
insert into posts (title, body, user_id) values ('Frogs for Snakes', 'Toxic effects of unspecified organic solvent', 1);
insert into posts (title, body, user_id) values ('Fail Safe', 'Dislocation of distal end of right ulna, subsequent encounter', 1);
insert into posts (title, body, user_id) values ('Tortured, The', 'Person injured in other specified (collision)(noncollision) transport accidents involving nonmotor vehicle, nontraffic, subsequent encounter', 1);
insert into posts (title, body, user_id) values ('Doctor at Large', 'Nondisplaced segmental fracture of shaft of ulna, left arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 1);
insert into posts (title, body, user_id) values ('Pride and Glory', 'Maternal care for known or suspected placental insufficiency, unspecified trimester, other fetus', 1);
insert into posts (title, body, user_id) values ('Standard Operating Procedure', 'Nondisplaced unspecified condyle fracture of lower end of right femur, sequela', 1);
insert into posts (title, body, user_id) values ('Dances With the Dragons ( Yu long gong wu)', 'Diplacusis, left ear', 1);
insert into posts (title, body, user_id) values ('Spies (Spione)', 'Other injury of ureter, subsequent encounter', 1);
insert into posts (title, body, user_id) values ('Ordet (Word, The)', 'Traumatic subdural hemorrhage with loss of consciousness of 31 minutes to 59 minutes, sequela', 1);
insert into posts (title, body, user_id) values ('Deadly Friend', 'Juvenile osteochondrosis of metatarsus, left foot', 1);
insert into posts (title, body, user_id) values ('Viva Riva!', 'Subacute cutaneous lupus erythematosus', 2);
insert into posts (title, body, user_id) values ('Oliver!', 'Kaposi''s sarcoma of unspecified lung', 2);
insert into posts (title, body, user_id) values ('Wild at Heart', 'Central perforation of tympanic membrane, bilateral', 1);
insert into posts (title, body, user_id) values ('Second Woman, The', 'Passenger in three-wheeled motor vehicle injured in collision with fixed or stationary object in traffic accident, initial encounter', 1);
insert into posts (title, body, user_id) values ('Golden Boys, The', 'Diffuse traumatic brain injury with loss of consciousness of 6 hours to 24 hours', 1);
insert into posts (title, body, user_id) values ('Killer Elite', 'Fall into other water striking water surface causing drowning and submersion', 2);
insert into posts (title, body, user_id) values ('Nightmare on Elm Street 4: The Dream Master, A', 'Epidermolysis bullosa due to drug', 2);
insert into posts (title, body, user_id) values ('Container', 'Fracture of neck, unspecified', 1);
insert into posts (title, body, user_id) values ('Unintentional Kidnapping of Mrs. Elfriede Ott, The (Die Unabsichtliche Entführung der Frau Elfriede Ott)', 'Unspecified injury of blood vessel of unspecified thumb, sequela', 2);
insert into posts (title, body, user_id) values ('Crackers', 'Injury of unspecified nerve at hip and thigh level, left leg, subsequent encounter', 2);
insert into posts (title, body, user_id) values ('Very Ordinary Couple (Yeonaeui Wondo)', 'Other specified arthritis, hand', 1);
insert into posts (title, body, user_id) values ('Mortdecai', 'Adhesive capsulitis of shoulder', 1);
insert into posts (title, body, user_id) values ('Ice House, The', 'Occupant (driver) (passenger) of three-wheeled motor vehicle injured in unspecified nontraffic accident, sequela', 1);
insert into posts (title, body, user_id) values ('All About Lily Chou-Chou (Riri Shushu no subete)', 'Other fracture of first metacarpal bone', 1);
insert into posts (title, body, user_id) values ('One 2 Ka 4', 'External constriction of right eyelid and periocular area, sequela', 1);
insert into posts (title, body, user_id) values ('Fresh Horses', 'Laceration of unspecified intra-abdominal organ, subsequent encounter', 1);
insert into posts (title, body, user_id) values ('Oblivion Island: Haruka and the Magic Mirror (Hottarake no shima - Haruka to maho no kagami)', 'Myocardial degeneration', 1);
insert into posts (title, body, user_id) values ('Feiern', 'Other mechanical complication of bile duct prosthesis', 2);
insert into posts (title, body, user_id) values ('Molly', 'Poisoning by barbiturates, assault, initial encounter', 2);
insert into posts (title, body, user_id) values ('Battle Beyond the Stars', 'Unspecified injury of unspecified blood vessel at forearm level, unspecified arm, initial encounter', 2);
insert into posts (title, body, user_id) values ('Keeper, The', 'Age-related osteoporosis with current pathological fracture, left hand, sequela', 1);
insert into posts (title, body, user_id) values ('Vampyros Lesbos (Vampiras, Las)', 'Dislocation of unspecified acromioclavicular joint, greater than 200% displacement, sequela', 2);
insert into posts (title, body, user_id) values ('Blind Horizon', 'Peripheral corneal degeneration', 2);
insert into posts (title, body, user_id) values ('Pale Rider', 'Secondary syphilitic hepatitis', 2);
insert into posts (title, body, user_id) values ('Lost Horizon', 'Puncture wound without foreign body, user_id of penis', 1);
insert into posts (title, body, user_id) values ('Magic Hunter (Büvös vadász)', 'Other problems related to employment', 1);

